name = "email-worker-h3"
main = "src/worker.ts"
compatibility_date = "2024-06-02"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
# Biến môi trường (ENV vars)
[vars]
USERNAME = ""
PASSWORD = ""